services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5001:5000"
    environment:
      - MONGO_URI=mongodb://db:27017/document-vault
      - AWS_BUCKET_NAME=mybucket
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
    depends_on:
      - db
      - s3

  db:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  s3:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data

volumes:
  mongodb_data:
  s3_data:
